services:
  rb-api_gateway:
    build:
      context: ./rb-api_gateway
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./rb-api_gateway/src:/rb-api_gateway/src

  rb-user:
    build:
      context: ./rb-user
    networks:
      - app-network
    volumes:
      - ./rb-user:/rb-user
  
  rb-bird:
    build:
      context: ./rb-bird
    networks:
      - app-network
    volumes:
      - ./rb-bird:/rb-bird

networks:
  app-network:
    driver: bridge
